version: '3'
services:
  nginx:
    container_name: acbw.me
    restart: always
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    volumes:
      - ./public:/usr/share/nginx/html:ro
    expose:
      - "80"
      - "443"
    networks:
      - nginx_proxy_stratas

  hugo:
    container_name: hugo.acbw.me
    image: klakegg/hugo:0.92.1-ext-ubuntu
    volumes:
      - ".:/src"

networks:
  nginx_proxy_stratas:
    external: true
